# Generated by Django 5.0.2 on 2024-02-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=255
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("black", "Black or African American"),
                            ("hispanic", "Hispanic or Latino"),
                            ("asian", "Asian"),
                            ("native", "American Indian or Alaska Native"),
                            ("hawaiian", "Native Hawaiian or Other Pacific Islander"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=500,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("hair_color", models.CharField(max_length=255)),
                ("eye_color", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("missing", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vigilant", "Vigilant"),
                            ("amber", "AMBER"),
                            ("silver", "Silver"),
                            ("endangered", "Endangered Missing Person"),
                            ("blue", "Blue"),
                            ("camo", "Camo"),
                        ],
                        max_length=255,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(max_length=500)),
                ("contact", models.CharField(max_length=500)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
