# Generated by Django 5.0.2 on 2024-02-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_person_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="alert",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="static/photos"),
        ),
    ]
