# Generated by Django 5.0.2 on 2024-02-25 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="eye_color",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="hair_color",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="height",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("white", "White"),
                    ("black", "Black or African American"),
                    ("hispanic", "Hispanic or Latino"),
                    ("asian", "Asian"),
                    ("native", "American Indian or Alaska Native"),
                    ("hawaiian", "Native Hawaiian or Other Pacific Islander"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="weight",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
