# Generated by Django 5.0.2 on 2024-02-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacialDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_image", models.CharField(max_length=500)),
                ("target_image", models.CharField(max_length=500)),
                ("found_match", models.BooleanField()),
                ("box_result", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "cropped_result",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
