# Generated by Django 5.0.2 on 2024-02-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_facialdetectionresult"),
        ("web", "0005_remove_alert_title_user_trusted_contacts_and_more"),
    ]

    operations = []
