# Generated by Django 5.0.2 on 2024-02-25 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_merge_20240225_0855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trusted_contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="trusted_contact_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="InformationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/reports"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.person",
                    ),
                ),
            ],
        ),
    ]
