# Generated by Django 5.0.2 on 2024-02-25 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_person_date_of_birth_alter_person_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="contact",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="location",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.person",
            ),
        ),
    ]
