# Generated by Django 5.0.2 on 2024-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_persondescriptionresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleIdentificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                ("box_result", models.CharField(blank=True, max_length=500, null=True)),
                ("cropped_result", models.CharField(max_length=500)),
            ],
        ),
    ]
