# Generated by Django 5.0.2 on 2024-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_vehicleidentificationresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleGetAllResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=500)),
                ("person_image", models.CharField(max_length=500)),
            ],
        ),
    ]
